version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE:-picking}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE:-picking}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - picking-net

  picking-api:
    build:
      context: ../services/picking-api
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8000"
    networks:
      - picking-net
    volumes:
      - ../services/picking-api:/app
      - ../samples/abcxyz:/data/abcxyz:ro

  ui:
    build:
      context: ../services/ui
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    depends_on:
      picking-api:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - picking-net
    volumes:
      - ../services/ui:/app

networks:
  picking-net:
    driver: bridge

volumes:
  pgdata:
